version: '3'
volumes:
  node_modules:
services:
  fubar:
    build: .
    network_mode: "bridge"
    ports: 
     - "3000:3000"
     - "8000:8000"
     - "3001:3001"
    volumes:
     - "./:/usr/src/app"
     - "node_modules:/usr/src/app/node_modules"